name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  fluttertoast: ^8.0.9  # Ensure this line is added

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/onboarding.png
    - assets/crops.png
    - assets/location.png
    - assets/back.png
    - assets/home.png
    - assets/search.png
    - assets/agric.png
    - assets/select soil.png
    - assets/wheat.png
    - assets/paddy.png
    - assets/apple.png
    - assets/corn.png
    - assets/banana.png
    - assets/potato.png
    - assets/sugarcane.png
    - assets/tomato.png
    - assets/grapes.png
    - assets/black.png
    - assets/red.png
    - assets/alluvial.png
    - assets/forest.png
    - assets/desert.png
    - assets/podzol.png
    - assets/salinealkaline.png
    - assets/andosol.png
    - assets/tundra.png
    - assets/uzhavan.png
    - assets/thanjavur.png
    - assets/theni.png
    - assets/villupuram.png
    - assets/salem.png
    - assets/trichy.png
    - assets/nagapattinam.png
    - assets/madurai.png
    - assets/erode.png
    - assets/coimbatore.png
    - assets/analysis.png